const dataLevel1 = [
  {
    id: 1,
    name: "Bataille de Bob-omb",
    link: "https://www.youtube.com/embed/myfIK0WmhY0",
    world: 1,
    level: 1,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
  {
    id: 2,
    name: "Course contre Koopa Rapido",
    link: "https://www.youtube.com/embed/t46MH8GJCIw",
    world: 1,
    level: 2,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
  {
    id: 3,
    name: "Canon vers l’ile perchee",
    link: "https://www.youtube.com/embed/wLB418puRm0",
    world: 1,
    level: 3,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
  {
    id: 4,
    name: "Les 8 pieces rouges",
    link: "https://www.youtube.com/embed/LnnTj-5HQ94",
    world: 1,
    level: 4,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
  {
    id: 5,
    name: "Vol du mario aile",
    link: "https://www.youtube.com/embed/SKMDRtAJjkM",
    world: 1,
    level: 5,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
  {
    id: 6,
    name: "Derriere la cage de chomp",
    link: "https://www.youtube.com/embed/rzsWLrBinmE",
    world: 1,
    level: 6,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
];

const dataLevel2 = [
  {
    id: 7,
    name: "Destruction du gros whomp",
    link: "https://www.youtube.com/embed/H_4J37jyva0",
    world: 2,
    level: 1,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
  {
    id: 8,
    name: "En haut de la forteresse",
    link: "https://www.youtube.com/embed/7P4Iqj90Bpk",
    world: 2,
    level: 2,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
  {
    id: 9,
    name: "Canon vers les cieux",
    link: "https://www.youtube.com/embed/NZ_BqbZSF-I",
    world: 2,
    level: 3,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
  {
    id: 10,
    name: "Pieces rouges dans les airs",
    link: "https://www.youtube.com/embed/pQEulFkhvsU",
    world: 2,
    level: 4,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
  {
    id: 11,
    name: "Tombez dans la cage perchee",
    link: "https://www.youtube.com/embed/QF6ZRGVqTGU",
    world: 2,
    level: 5,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
  {
    id: 12,
    name: "Canon vers le mur",
    link: "https://www.youtube.com/embed/nw5Bs78eafQ",
    world: 2,
    level: 6,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
];

const dataLevel3 = [
  {
    id: 13,
    name: "Pillez le bateau coule",
    link: "https://www.youtube.com/embed/KM2z-ST0Bms",
    world: 3,
    level: 1,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
  {
    id: 14,
    name: " L'anguille veut faire joujou",
    link: "https://www.youtube.com/embed/_7yzzrG20kE",
    world: 3,
    level: 2,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
  {
    id: 15,
    name: "Tresor dans la caverne",
    link: "https://www.youtube.com/embed/_KXYkgXdlMs",
    world: 3,
    level: 3,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
  {
    id: 16,
    name: "Pieces rouges a bord",
    link: "https://www.youtube.com/embed/xLqtSS1xZFs",
    world: 3,
    level: 4,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
  {
    id: 17,
    name: "Canon vers les pilliers",
    link: "https://www.youtube.com/embed/RCFCx4qhJZY",
    world: 3,
    level: 5,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
  {
    id: 18,
    name: "Dans le geyser",
    link: "https://www.youtube.com/embed/c42PSoN6FLY",
    world: 3,
    level: 6,
    author: "Drgoku282",
    link_author: "https://www.youtube.com/c/drgoku282/featured",
  },
];
const dataLevel4 = [
  {
    id: 19,
    name: "Glissade sur glace",
    link: "https://www.youtube.com/embed/G6fOUSoL_Og",
    world: 4,
    level: 1,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
  {
    id: 20,
    name: "Petit pingouin perdu",
    link: "https://www.youtube.com/embed/EWmMUTawK7Q",
    world: 4,
    level: 2,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
  {
    id: 21,
    name: "Course du pingouin",
    link: "https://www.youtube.com/embed/j8l12Vc1r3M",
    world: 4,
    level: 3,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
  {
    id: 22,
    name: "8 pieces rouges givrees",
    link: "https://www.youtube.com/embed/QSFI_JhIrmU",
    world: 4,
    level: 4,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 23,
    name: "Bonhomme de neige sans tete",
    link: "https://www.youtube.com/embed/u0c_rDwliGA?list=PL64DF31117806C5C2",
    world: 4,
    level: 5,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 24,
    name: "Murs pour rebondir",
    link: "https://www.youtube.com/embed/QOhQQb3dtiM?list=PL64DF31117806C5C2",
    world: 4,
    level: 6,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
];
const dataLevel5 = [
  {
    id: 25,
    name: "Cherchez le Big Boo",
    link: "https://www.youtube.com/embed/VUBSF6QoE1w?list=PL64DF31117806C5C2",
    world: 5,
    level: 1,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 26,
    name: "Manege des Boos pas beaux",
    link: "https://www.youtube.com/embed/rSUwk7IPw3U?list=PL64DF31117806C5C2",
    world: 5,
    level: 2,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 27,
    name: "Secret des livres hantes",
    link: "https://www.youtube.com/embed/SCG2YHnXix8?list=PL64DF31117806C5C2",
    world: 5,
    level: 3,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 28,
    name: "Trouvez les 8 pieces rouges",
    link: "https://www.youtube.com/embed/DkOBJp0o61c?list=PL64DF31117806C5C2",
    world: 5,
    level: 4,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 29,
    name: "Balcon de Big Boo",
    link: "https://www.youtube.com/embed/T1dJNCvrSTs?list=PL64DF31117806C5C2",
    world: 5,
    level: 5,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 30,
    name: "Un oeil sur les salles secretes",
    link: "https://www.youtube.com/embed/Cn9AIXMo9Us",
    world: 5,
    level: 6,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
];
const dataLevel6 = [
  {
    id: 31,
    name: "Gros Bibi de la caverne",
    link: "https://www.youtube.com/embed/DwkX5UvsALQ",
    world: 6,
    level: 1,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 32,
    name: "Chariot pour pieces rouges",
    link: "https://www.youtube.com/embed/mfUFEFlGvkY",
    world: 6,
    level: 2,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 33,
    name: "Course de metal mario",
    link: "https://www.youtube.com/embed/_aEcM3lsseo?list=PL64DF31117806C5C2",
    world: 6,
    level: 3,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 34,
    name: "Dans le labyrinthe toxique",
    link: "https://www.youtube.com/embed/cHlz8yD7BEE?list=PL64DF31117806C5C2",
    world: 6,
    level: 4,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 35,
    name: "Au-dessus des gaz...",
    link: "https://www.youtube.com/embed/hHB-NPQPhro?list=PL64DF31117806C5C2",
    world: 6,
    level: 5,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 36,
    name: "Attention aux boulets",
    link: "https://www.youtube.com/embed/8d48zogkdSc?list=PL64DF31117806C5C2",
    world: 6,
    level: 6,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
];

const dataLevel7 = [
  {
    id: 37,
    name: "Cramez le gros moche",
    link: "https://www.youtube.com/embed/DiZcLupR0hg",
    world: 7,
    level: 1,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
  {
    id: 38,
    name: "Poussez les petits moches",
    link: "https://www.youtube.com/embed/5h7ekyg0V6w",
    world: 7,
    level: 2,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
  {
    id: 39,
    name: "Puzzle de 8 pieces rouges",
    link: "https://www.youtube.com/embed/g-AJT28VQbA",
    world: 7,
    level: 3,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
  {
    id: 40,
    name: "Balade sur la buche",
    link: "https://www.youtube.com/embed/AIYoIlnxSEc",
    world: 7,
    level: 4,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
  {
    id: 41,
    name: "Chaud dans le volcan",
    link: "https://www.youtube.com/embed/7V-HTYJ7ZIw",
    world: 7,
    level: 5,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
  {
    id: 42,
    name: "Ascenceur dans le volcan",
    link: "https://www.youtube.com/embed/0Fl05MnuRJY",
    world: 7,
    level: 6,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
];

const dataLevel8 = [
  {
    id: 43,
    name: "Dans les griffes du vautour",
    link: "https://www.youtube.com/embed/kPLpYOjMz_s",
    world: 8,
    level: 1,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
  {
    id: 44,
    name: "Au sommet de la pyramide",
    link: "https://www.youtube.com/embed/ysMW0ODNw_o",
    world: 8,
    level: 2,
    author: "Serious Soluce",
    link_author: "https://www.youtube.com/channel/UCwXVIWu7aFsAk1MzrwyKIgQ",
  },
  {
    id: 45,
    name: "Dans l'ancienne pyramide",
    link: "https://www.youtube.com/embed/rkClyrNgLSs?list=PL64DF31117806C5C2",
    world: 8,
    level: 3,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 46,
    name: "Les 4 piliers de la foi",
    link: "https://www.youtube.com/embed/eXzxgq_QASA?list=PL64DF31117806C5C2",
    world: 8,
    level: 4,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 47,
    name: "Vol vers les 8 pieces rouges",
    link: "https://www.youtube.com/embed/vDykruH3iJQ?list=PL64DF31117806C5C2",
    world: 8,
    level: 5,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 48,
    name: "Enigme de la pyramide",
    link: "https://www.youtube.com/embed/d6EbcI2FCZk?list=PL64DF31117806C5C2",
    world: 8,
    level: 6,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
];

const dataLevel9 = [
  {
    id: 49,
    name: "Sous-marin de Bowser",
    link: "https://www.youtube.com/embed/mMDTaTI_UsU?list=PL64DF31117806C5C2",
    world: 9,
    level: 1,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 50,
    name: "Coffres dans le courant",
    link: "https://www.youtube.com/embed/MFHag4qWN28?list=PL64DF31117806C5C2",
    world: 9,
    level: 2,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 51,
    name: "Perches pour pieces rouges",
    link: "https://www.youtube.com/embed/XjHCnXICfDs?list=PL64DF31117806C5C2",
    world: 9,
    level: 3,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 52,
    name: "Dans le geyser",
    link: "https://www.youtube.com/embed/KCdeQYza6dg?list=PL64DF31117806C5C2",
    world: 9,
    level: 4,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 53,
    name: "Recompense de la raie",
    link: "https://www.youtube.com/embed/e7Da-30rCHw?list=PL64DF31117806C5C2",
    world: 9,
    level: 5,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 54,
    name: "Association de casquettes...",
    link: "https://www.youtube.com/embed/kCrYwxoWQ0s?list=PL64DF31117806C5C2",
    world: 9,
    level: 6,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
];
const dataLevel10 = [
  {
    id: 55,
    name: "Grosse tete du bonhomme",
    link: "https://www.youtube.com/embed/qU33WYaQyXI?list=PL64DF31117806C5C2",
    world: 10,
    level: 1,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 56,
    name: "Combattez le gros moche givre",
    link: "https://www.youtube.com/embed/fMwAul7xl-k?list=PL64DF31117806C5C2",
    world: 10,
    level: 2,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 57,
    name: "Dans le glacon",
    link: "https://www.youtube.com/embed/sQUHfe_oqt4?list=PL64DF31117806C5C2",
    world: 10,
    level: 3,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 58,
    name: "Vrille depuis le lac",
    link: "https://www.youtube.com/embed/Ds4EBXgwpbs?list=PL64DF31117806C5C2",
    world: 10,
    level: 4,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 59,
    name: "Carapace pour pieces rouges",
    link: "https://www.youtube.com/embed/DqJTB7SQxg0?list=PL64DF31117806C5C2",
    world: 10,
    level: 5,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 60,
    name: "Dans l'igloo",
    link: "https://www.youtube.com/embed/niuWQrIIuS8?list=PL64DF31117806C5C2",
    world: 10,
    level: 6,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
];
const dataLevel11 = [
  {
    id: 61,
    name: "Mini plates-formes fléchees !",
    link: "https://www.youtube.com/embed/GgQA-1qx5bE?list=PL64DF31117806C5C2",
    world: 11,
    level: 1,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 62,
    name: "Sur les toits",
    link: "https://www.youtube.com/embed/-dNi1d8dkTs?list=PL64DF31117806C5C2",
    world: 11,
    level: 2,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 63,
    name: "Enigme des chiffres caches",
    link: "https://www.youtube.com/embed/LZQVoRSKc5o?list=PL64DF31117806C5C2",
    world: 11,
    level: 3,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 64,
    name: "Ascenseur express !",
    link: "https://www.youtube.com/embed/djA20svH2c0?list=PL64DF31117806C5C2",
    world: 11,
    level: 4,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 65,
    name: "Pieces rouges: ville engloutie",
    link: "https://www.youtube.com/embed/w4rWogQhzEg?list=PL64DF31117806C5C2",
    world: 11,
    level: 5,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 66,
    name: "Course en ville",
    link: "https://www.youtube.com/embed/T0RBe6QPUfs?list=PL64DF31117806C5C2",
    world: 11,
    level: 6,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
];

const dataLevel12 = [
  {
    id: 67,
    name: "Escaladez la montagne",
    link: "https://www.youtube.com/embed/1xzHWbLL_0A?list=PL64DF31117806C5C2",
    world: 12,
    level: 1,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 68,
    name: "Mystere de la cage du singe",
    link: "https://www.youtube.com/embed/8YYPZnUiWAA?list=PL64DF31117806C5C2",
    world: 12,
    level: 2,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 69,
    name: "Pieces rouges sur champignon",
    link: "https://www.youtube.com/embed/XdLfh6p93-o?list=PL64DF31117806C5C2",
    world: 12,
    level: 3,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 70,
    name: "Paroi mysterieuse",
    link: "https://www.youtube.com/embed/Hx0Qg49Jja8?list=PL64DF31117806C5C2",
    world: 12,
    level: 4,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 71,
    name: "Panorama du pont",
    link: "https://www.youtube.com/embed/k4DNhU7UguY?list=PL64DF31117806C5C2",
    world: 12,
    level: 5,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 72,
    name: "Canon vers le champignon",
    link: "https://www.youtube.com/embed/bcDnstWz-u8?list=PL64DF31117806C5C2",
    world: 12,
    level: 6,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
];

const dataLevel13 = [
  {
    id: 73,
    name: "Detruisez les maxi-carnivores",
    link: "https://www.youtube.com/embed/vFlndNP4Zoo?list=PL64DF31117806C5C2",
    world: 13,
    level: 1,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 74,
    name: "Au sommet de l'ile des geants",
    link: "https://www.youtube.com/embed/iGdjS1KuQJM?list=PL64DF31117806C5C2",
    world: 13,
    level: 2,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 75,
    name: "Koopa Rapido, la vengeance",
    link: "https://www.youtube.com/embed/msdL17JXtnU?list=PL64DF31117806C5C2",
    world: 13,
    level: 3,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 76,
    name: "Cinq tout petits secrets",
    link: "https://www.youtube.com/embed/RohTOdveIss?list=PL64DF31117806C5C2",
    world: 13,
    level: 4,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 77,
    name: "Les pieces rouges du gigoteur",
    link: "https://www.youtube.com/embed/wRqZtc-CAW8?list=PL64DF31117806C5C2",
    world: 13,
    level: 5,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 78,
    name: "Enervez le gigoteur",
    link: "https://www.youtube.com/embed/fhBB3aEU_nw?list=PL64DF31117806C5C2",
    world: 13,
    level: 6,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
];

const dataLevel14 = [
  {
    id: 79,
    name: "Roulements dans la cage",
    link: "https://www.youtube.com/embed/65AJNfoz61o?list=PL64DF31117806C5C2",
    world: 14,
    level: 1,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 80,
    name: "Les trous et le pendule",
    link: "https://www.youtube.com/embed/50uYj-TeWCc?list=PL64DF31117806C5C2",
    world: 14,
    level: 2,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 81,
    name: "Chevauchez l'aiguille",
    link: "https://www.youtube.com/embed/P_RC48PFT90?list=PL64DF31117806C5C2",
    world: 14,
    level: 3,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 82,
    name: "L'ecrabouilleur",
    link: "https://www.youtube.com/embed/_OD1bd_pInw?list=PL64DF31117806C5C2",
    world: 14,
    level: 4,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 83,
    name: "Sauts synchronises",
    link: "https://www.youtube.com/embed/tpz5Av_N8j4?list=PL64DF31117806C5C2",
    world: 14,
    level: 5,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 84,
    name: "L'heure pile pour les pieces",
    link: "https://www.youtube.com/embed/jxcjp7rs9b8?list=PL64DF31117806C5C2",
    world: 14,
    level: 6,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
];

const dataLevel15 = [
  {
    id: 85,
    name: "Croisiere sur l'arc-en-ciel",
    link: "https://www.youtube.com/embed/C-ab0eAT8Ls?list=PL64DF31117806C5C2",
    world: 15,
    level: 1,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 86,
    name: "Manoir dans les airs",
    link: "https://www.youtube.com/embed/lzejfC9QAGM?list=PL64DF31117806C5C2",
    world: 15,
    level: 2,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 87,
    name: "Labyrinthe des pieces rouges",
    link: "https://www.youtube.com/embed/JZyLfmuQ2v8?list=PL64DF31117806C5C2",
    world: 15,
    level: 3,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 88,
    name: "Balançoire celeste",
    link: "https://www.youtube.com/embed/oIsIM7yzVpA?list=PL64DF31117806C5C2",
    world: 15,
    level: 4,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 89,
    name: "Vicieux triangles!",
    link: "https://www.youtube.com/embed/KL3si7hv55Q?list=PL64DF31117806C5C2",
    world: 15,
    level: 5,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
  {
    id: 90,
    name: "L'arc-en-ciel et au-dela",
    link: "https://www.youtube.com/embed/Mj0GYrAyL_4?list=PL64DF31117806C5C2",
    world: 15,
    level: 6,
    author: "KrixixGames",
    link_author: "https://www.youtube.com/user/KrixixGames",
  },
];

const dataArray = [
  dataLevel1,
  dataLevel2,
  dataLevel3,
  dataLevel4,
  dataLevel5,
  dataLevel6,
  dataLevel7,
  dataLevel8,
  dataLevel9,
  dataLevel10,
  dataLevel11,
  dataLevel12,
  dataLevel13,
  dataLevel14,
  dataLevel15,
];

export default dataArray;
